"""
Base mixins for all domain models.

Decision D-C02-1: All entities use UUID (UUIDv7) generated by new_uuid.
Decision D-C02-2: TimestampUUIDMixin = id + created_at + updated_at.
                  SoftDeleteMixin = deleted_at (applied ONLY to Proveedor, Factura, Pago).
                  Usuario and FacturaItem do NOT carry deleted_at.

Implementation note on SQLModel mixins — updated_at server-side onupdate:

SQLModel (0.0.19+) with Pydantic v2 does not support declared_attr (Pydantic
requires annotations). The workaround for per-row `updated_at` refresh in a
mixin is to use `sa_column_kwargs` with only the keys that don't conflict with
SQLModel's own column construction.

For `onupdate`, we pass it in `sa_column_kwargs`. SQLModel calls
`Column(*positional_type_args, **sa_column_kwargs)` after determining the
SQLAlchemy type from the Python annotation. As long as we don't pass `type_`
in sa_column_kwargs, it works correctly.

The `server_default` and `onupdate` keys are valid Column kwargs and don't
conflict with SQLModel's type inference.
"""

import uuid
from datetime import datetime, timezone
from typing import Optional

from sqlmodel import Field, SQLModel
from sqlalchemy import text

from app.core.uuid_utils import new_uuid


def _utcnow() -> datetime:
    """Return current UTC time (timezone-aware)."""
    return datetime.now(timezone.utc)


class TimestampUUIDMixin(SQLModel):
    """
    Shared base mixin providing:
    - id: UUID (UUIDv7 via new_uuid, primary key)
    - created_at: timestamp populated at insert
    - updated_at: timestamp populated at insert and updated on UPDATE

    Does NOT include saldo, estado, or deleted_at.
    """

    id: uuid.UUID = Field(
        default_factory=new_uuid,
        primary_key=True,
        nullable=False,
    )
    created_at: datetime = Field(
        default_factory=_utcnow,
        nullable=False,
        sa_column_kwargs={"server_default": text("now()")},
    )
    updated_at: datetime = Field(
        default_factory=_utcnow,
        nullable=False,
        sa_column_kwargs={
            "server_default": text("now()"),
            "onupdate": _utcnow,
        },
    )


class SoftDeleteMixin(SQLModel):
    """
    Optional soft-delete extension.

    Applied only to: Proveedor, Factura, Pago.
    NOT applied to: Usuario, FacturaItem.

    Convention: deleted_at IS NULL → active; deleted_at IS NOT NULL → deleted.
    """

    deleted_at: Optional[datetime] = Field(
        default=None,
        nullable=True,
    )


__all__ = ["TimestampUUIDMixin", "SoftDeleteMixin"]
